// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHah3r4tliARlwLfYV7rc5k3gjSX7YFa4',
    appId: '1:293742231117:web:375a0d1f1523c35049a604',
    messagingSenderId: '293742231117',
    projectId: 'firestore-4d4f5',
    authDomain: 'firestore-4d4f5.firebaseapp.com',
    storageBucket: 'firestore-4d4f5.appspot.com',
    measurementId: 'G-WRE7SWWE63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWV-EZybR6N6lcrkoHLdLivcbTVFBzz_k',
    appId: '1:293742231117:android:1363e7846faa8a5849a604',
    messagingSenderId: '293742231117',
    projectId: 'firestore-4d4f5',
    storageBucket: 'firestore-4d4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWywDRWPq_-6jEyGb0y565jhFGI7gstQ',
    appId: '1:293742231117:ios:84edec0c70620a9249a604',
    messagingSenderId: '293742231117',
    projectId: 'firestore-4d4f5',
    storageBucket: 'firestore-4d4f5.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWywDRWPq_-6jEyGb0y565jhFGI7gstQ',
    appId: '1:293742231117:ios:84edec0c70620a9249a604',
    messagingSenderId: '293742231117',
    projectId: 'firestore-4d4f5',
    storageBucket: 'firestore-4d4f5.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHah3r4tliARlwLfYV7rc5k3gjSX7YFa4',
    appId: '1:293742231117:web:d8331654ec06869149a604',
    messagingSenderId: '293742231117',
    projectId: 'firestore-4d4f5',
    authDomain: 'firestore-4d4f5.firebaseapp.com',
    storageBucket: 'firestore-4d4f5.appspot.com',
    measurementId: 'G-N6T8774KCF',
  );
}
